// src/pages/Clients.tsx
import Layout from "../components/Layout";
import NavBar from "../components/NavBar";
import Title from "../components/Title";
import { FiPlusSquare } from "solid-icons/fi";
import SearchBar from "../components/SearchBar";
import { createMemo, createSignal } from "solid-js";
import { List, ListItem } from "../components/List";
import Paper from "../components/Paper";
import { Transition } from "solid-transition-group";
import { clientsStore } from "../stores/clients";
import { Avatar } from "../components/Avatar";
import { PlugText } from "../components/Plugs";
import { Link } from "solid-app-router";

function ClientListPlug() {
	return (
		<List title="Список клиентов" margin="5px 0">
			{Array(10)
				.fill(0)
				.map(() => (
					<ListItem
						avatar={<Avatar isPlug={true} />}
						title={<PlugText size={80} height={"0.7em"} />}
						content={<PlugText size={160} />}
					/>
				))}
		</List>
	);
}

function Clients() {
	const [searchQuery, setSearchQuery] = createSignal("");
	const { clients } = clientsStore;

	const filteredClients = createMemo(() => {
		if (!searchQuery()) return clients.list;
		return clients.list.filter(
			client =>
				client.name.toLowerCase().includes(searchQuery().toLowerCase()) ||
				client.description.toLowerCase().includes(searchQuery().toLowerCase())
		);
	});

	const ClientList = () => {
		return (
			<List title="Список клиентов" margin="5px 0">
				{filteredClients().map(client => (
					<ListItem
						href={`/client/${client.id}`}
						avatar={<Avatar name={client.name} />}
						title={client.name}
						content={client.description.trim() ? client.description : "empty description"}
					/>
				))}

				{filteredClients().length ? <></> : <ListItem content="Список пуст"></ListItem>}
			</List>
		);
	};

	return (
		<Layout
			title={
				<Title
					rightChildren={
						<Link href="/client/create">
							<FiPlusSquare size={28} />
						</Link>
					}
					title="Клиенты"
				/>
			}
			navBar={<NavBar />}>
			<Paper fixedContent={<SearchBar onInput={value => setSearchQuery(value)} />}>
				<Transition
					mode="outin"
					onEnter={(el, done) => {
						const a = el.animate([{ opacity: 0 }, { opacity: 1 }], { duration: 500 });
						a.finished.then(done);
					}}
					onExit={(el, done) => {
						const a = el.animate([{ opacity: 1 }, { opacity: 0 }], { duration: 500 });
						a.finished.then(done);
					}}>
					{clients.isLoading ? <ClientListPlug /> : <ClientList />}
				</Transition>
			</Paper>
		</Layout>
	);
}

export default Clients;

// src/pages/Clients.svelte
<script>
import Avatar from "../components/Avatar.svelte";
import List from "../components/List.svelte";
import PageContainer from "../components/PageContainer.svelte";
import SearchBar from "../components/SearchBar.svelte";
import ChevronRight32 from "carbon-icons-svelte/lib/ChevronRight32";
import { link } from "svelte-spa-router";
import FabButton from "../components/FabButton.svelte";
import EmptyMessage from "../components/EmptyMessage.svelte";
import { useStoreon } from "@storeon/svelte";

const { clients } = useStoreon("clients");
let searchQuery = "";
$: filteredClients = $clients.filter(
  ({ name, description }) =>
    name.toLowerCase().includes(searchQuery) ||
    description.toLowerCase().includes(searchQuery)
);

const handleSearchInput = event => {
  searchQuery = event.target.value;
};
</script>

<PageContainer title="Клиенты">
  <SearchBar on:input="{handleSearchInput}" />
  <FabButton href="/clients/create" />
  {#if filteredClients.length}
    <List items="{filteredClients}" let:item>
      <li>
        <a href="{`/clients/${item.id}`}" use:link class="list__event-button">
          Open client
        </a>

        <div class="list__item-avatar">
          <Avatar initials="{item.name}" />
        </div>
        <div class="list__item">
          <div class="list__item-content">
            <h2>{item.name}</h2>
            <h3>{item.description}</h3>
          </div>
          <div class="list__item-end">
            <ChevronRight32 />
          </div>
        </div>
      </li>
    </List>
  {:else}
    <EmptyMessage />
  {/if}
</PageContainer>
