// src/pages/Records.svelte
<style>
.list__item-content {
  width: 100%;
}

.services {
  margin-top: 10px;
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}

.services__service {
  background: #ffe8ff;
  color: #0a0a0a;
  border-radius: 5px;
  padding: 3px 10px;
  font-size: 0.9em;
  font-weight: initial;
}

.client {
  display: flex;
}

.client__avatar {
  margin-right: 8px;
}

.client__info-time {
  color: rgb(49, 49, 49);
  font-weight: normal;
  font-size: 0.8em;
}

.client__price {
  flex-grow: 1;
  text-align: right;
}
</style>

<script>
import { useStoreon } from "@storeon/svelte";

import DateSelecter from "../components/DateSelecter.svelte";
import List from "../components/List.svelte";
import Title from "../components/Title.svelte";
import { link } from "svelte-spa-router";
import EmptyMessage from "../components/EmptyMessage.svelte";
import { format } from "date-fns";
import Avatar from "../components/Avatar.svelte";

const { records, clients, services } = useStoreon(
  "records",
  "recordsDate",
  "clients",
  "services"
);

$: recordForList = $records.map(record => {
  const servicesList = $services.filter(({ id }) => record.serviceIds.includes(id));

  return {
    ...record,
    client: $clients.find(({ id }) => id === record.clientId),
    services: servicesList.map(({ name }) => name),
    summPriceOfServices: servicesList.reduce((acc, { price }) => acc + +price, 0),
  };
});
</script>

<Title title="Мои записи" />
<DateSelecter />
{#if recordForList.length}
  <List items="{recordForList}" let:item>
    <li>
      <a href="{`/records/${item.id}`}" use:link class="list__event-button">
        Open record
      </a>

      <div class="list__item">
        <div class="list__item-content">
          <div class="client">
            <div class="client__avatar">
              <Avatar initials="{item.client?.name || 'Deleted Client'}" />
            </div>
            <div class="client__info">
              <div class="client__info-name">
                {item.client?.name || "Deleted Client"}
              </div>
              <div class="client__info-time">
                {format(item.date, "hh:mm")}
              </div>
            </div>
            <div class="client__price">
              {item.summPriceOfServices}₽
            </div>
          </div>
          <div class="services">
            {#each item.services as service}
              <div class="services__service">{service}</div>
            {/each}
          </div>
        </div>
      </div>
    </li>
  </List>
{:else}
  <EmptyMessage />
{/if}

// src/pages/Records.tsx
import { format } from "date-fns";
import { Link } from "solid-app-router";
import { For, Match, Switch, createMemo } from "solid-js";

import { Avatar } from "../components/Avatar";
import { Badge, BadgeGrid } from "../components/Badge";
import { Calendar } from "../components/Calendar";
import { Card, CardAvatar, CardHeader, CardInfo, CardMainRow, CardSecondRow } from "../components/Card";
import { Layout } from "../components/Layout";
import { List, ListItem, ListItemBetweenContent } from "../components/List";
import { NavBar } from "../components/NavBar";
import { Paper } from "../components/Paper";
import { Title } from "../components/Title";
import titleStyles from "../components/modules/Title.module.css";

import { Client } from "../storage/client";
import { Record } from "../storage/record";
import { Service } from "../storage/service";
import { useStore } from "../stores";

type RecordItemProps = { record: Record & { client: Client | undefined; services: Service[] } };

function RecordItem({ record }: RecordItemProps) {
	const { id, client, services, date } = record;

	function LeftContent() {
		return (
			<Card>
				<CardHeader>
					<CardAvatar>
						<Avatar imageSrc={client?.avatar} name={client?.name} />
						<div style={{ "font-size": "0.76em", "text-align": "center", "margin-top": "10px" }}>
							{format(date.toDate() || new Date(), "HH:mm")}
						</div>
					</CardAvatar>
					<CardInfo>
						<CardMainRow>{client?.name}</CardMainRow>
						<CardSecondRow>
							<BadgeGrid>
								<For each={services}>{service => <Badge>{service.name}</Badge>}</For>
							</BadgeGrid>
						</CardSecondRow>
					</CardInfo>
				</CardHeader>
			</Card>
		);
	}

	function RightContent() {
		return <span style="padding: 10px 0;">{services.reduce((acc, s) => acc + +s.price, 0)}руб.</span>;
	}

	return (
		<ListItem
			href={`/record/${id}`}
			content={
				<ListItemBetweenContent
					rightAlign="flex-start"
					leftContent={<LeftContent />}
					rightContent={<RightContent />}
				/>
			}
		/>
	);
}

function RecordsTitle() {
	return (
		<Title
			rightChildren={
				<Link class={titleStyles.navigateLink} href="/record/create">
					Добавить
				</Link>
			}
			title="Записи"
		/>
	);
}

export function Records() {
	const { records } = useStore("records");
	const { clients } = useStore("clients");
	const { services } = useStore("services");

	function filterByCurrentDay({ date }: Record) {
		const formatForEqual = "dd-MM-yyyy";
		return format(date.toDate(), formatForEqual) === format(records.currentDate, formatForEqual);
	}

	function fillRecord(record: Record) {
		return {
			...record,
			client: clients.list.find(c => c.id === record.clientId),
			services: services.list.filter(s => record.serviceIds.includes(s.id)),
		};
	}

	function sortByDate(currentRecord: Record, nextRecord: Record) {
		return currentRecord.date.seconds - nextRecord.date.seconds;
	}

	const currentDayRecords = createMemo(() => {
		return records.list.filter(filterByCurrentDay).map(fillRecord).sort(sortByDate);
	});

	const dayPriceSum = createMemo(() => {
		return currentDayRecords().reduce((acc, r) => {
			return acc + r.services.reduce((acc, { price }) => acc + +price, 0);
		}, 0);
	});

	function RecordsList() {
		return (
			<List margin="5px 0" title={`Потенциальный доход: ${dayPriceSum()} руб.`}>
				<For each={currentDayRecords()} fallback={<ListItem content="Список пуст" />}>
					{record => <RecordItem record={record} />}
				</For>
			</List>
		);
	}

	return (
		<Layout title={<RecordsTitle />} navBar={<NavBar />}>
			<Paper fixedContent={<Calendar />} margin="5px 0 0 0">
				<Switch>
					<Match when={records.isLoading}>
						<div>Загрузка...</div>
					</Match>
					<Match when={!records.isLoading}>
						<RecordsList />
					</Match>
				</Switch>
			</Paper>
		</Layout>
	);
}
